import { test, expect } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'

test.beforeEach(async ({ page }, info) => {
  await page.addInitScript(({ skipGuide }) => {
    if (skipGuide) localStorage.setItem('hl-guide-seen', 'true')
    else localStorage.removeItem('hl-guide-seen')
    localStorage.setItem('hl-language', 'en')
  }, { skipGuide: !info.title.startsWith('reduced motion') })
})
test('loads the real 3D experience and changes diagrams and relations without errors', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('?lang=en')
  await expect(page.locator('canvas')).toBeVisible()
  await expect(page.locator('.scene-number')).toHaveCount(10)
  await page.getByRole('button', { name: 'View', exact: true }).click()
  await page.getByRole('button', { name: 'Reading view', exact: true }).click()
  await page.waitForTimeout(1000)
  const canvas = await page.locator('canvas').boundingBox()
  await page.locator('canvas').click({ position: { x: canvas!.width / 2, y: canvas!.height / 2 } })
  await expect(page.locator('.selected-number')).toContainText('05')
  await expect(page.locator('.formula')).toHaveText('5 + 5 = 10')
  await page.getByRole('button', { name: 'Number 1', exact: true }).click()
  await expect(page.locator('.formula')).toHaveText('1 + 5 = 6')
  await page.getByRole('button', { name: 'Luoshu', exact: true }).click()
  await page.getByRole('button', { name: 'Balance', exact: true }).click()
  await expect(page.locator('.formula')).toHaveText('9 + 5 + 1 = 15')
  await page.getByRole('button', { name: 'Next', exact: true }).click()
  await expect(page.locator('.formula')).toHaveText('2 + 7 + 6 = 15')
  await page.getByRole('button', { name: 'Compare', exact: true }).click()
  await expect(page.locator('.scene-number')).toHaveCount(19)
  await expect(page.locator('.experience')).toHaveAttribute('data-mode', 'compare')
  expect(errors).toEqual([])
})
test('sources stay hidden until hover or focus, then show real bibliographic details', async ({ page }) => {
  await page.goto('?lang=en')
  await expect(page.locator('.source-popover')).toHaveCount(0)
  const mark = page.locator('.work-description .citation-mark')
  await mark.hover()
  await expect(page.locator('.source-popover')).toContainText('《易学启蒙》')
  await expect(page.locator('.source-popover')).toContainText('本图书第一')
  await expect(page.locator('.source-popover')).toContainText('一與六共宗')
  await expect(page.locator('.source-popover a')).toHaveAttribute('href', /wikisource/)
  await page.mouse.move(700, 50)
  await expect(page.locator('.source-popover')).toHaveCount(0)
  await mark.focus()
  await expect(page.locator('.source-popover')).toBeVisible()
  await mark.press('Escape')
  await expect(page.locator('.source-popover')).toHaveCount(0)
})
test('preserves selection during language switching and provides history and concept reading', async ({ page }) => {
  await page.goto('?lang=en')
  await page.getByRole('button', { name: 'Number 6', exact: true }).click()
  await page.getByRole('button', { name: '切换至中文' }).click()
  await expect(page.locator('html')).toHaveAttribute('lang', 'zh-CN')
  await expect(page.locator('.selected-number')).toContainText('06')
  await page.getByRole('button', { name: '入门', exact: true }).click()
  await page.getByRole('tab', { name: '源流' }).click()
  await expect(page.getByRole('dialog')).toContainText('刘牧')
  await expect(page.getByRole('dialog')).toContainText('黄宗羲')
  await page.getByRole('tab', { name: '方法' }).click()
  await expect(page.getByRole('dialog')).toContainText('观察、辨数到读经')
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
})
test('provides complete SVG interaction when WebGL2 is unavailable', async ({ page }) => {
  await page.addInitScript(() => {
    const original = HTMLCanvasElement.prototype.getContext
    HTMLCanvasElement.prototype.getContext = function (this: HTMLCanvasElement, type: string, ...args: unknown[]) { return type === 'webgl2' ? null : original.apply(this, [type, ...args] as never) } as typeof original
  })
  await page.goto('?lang=en')
  await expect(page.locator('.experience')).toHaveAttribute('data-renderer', 'svg')
  await expect(page.locator('.diagram-svg')).toBeVisible()
  await page.getByRole('button', { name: 'Number 2', exact: true }).click()
  await expect(page.locator('.formula')).toHaveText('2 + 5 = 7')
  await page.getByRole('button', { name: 'Luoshu', exact: true }).click()
  await page.getByRole('button', { name: 'Balance', exact: true }).click()
  await expect(page.locator('.formula')).toContainText('15')
})
test('reduced motion introduction is stepped manually and can be skipped', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('?lang=en')
  await expect(page.locator('.guide-panel')).toBeVisible()
  await expect(page.locator('.guide-panel')).toContainText('Begin with a point')
  await page.getByRole('button', { name: 'Next', exact: true }).click()
  await expect(page.locator('.guide-panel')).toContainText('One and six')
  await page.getByRole('button', { name: 'Skip introduction' }).click()
  await expect(page.locator('.guide-panel')).toHaveCount(0)
  await expect(page.locator('.experience')).toHaveAttribute('data-mode', 'hetu')
  await page.getByRole('button', { name: 'Five phases', exact: true }).click()
  await expect(page.locator('.phase-formula')).toHaveText(/Wood\s+Fire/)
  await page.getByRole('button', { name: 'Next', exact: true }).click()
  await expect(page.locator('.phase-formula')).toHaveText(/Fire\s+Earth/)
  await page.getByRole('button', { name: 'Number 1', exact: true }).click()
  await expect(page.locator('.phase-formula')).toHaveText(/Water\s+Wood/)
  await page.getByRole('button', { name: 'Controlling', exact: true }).click()
  await expect(page.locator('.phase-formula')).toHaveText(/Water\s+Fire/)
  await page.getByRole('button', { name: 'Next', exact: true }).click()
  await expect(page.locator('.scene-number.active')).toHaveText(['2', '7'])
})
test('mobile controls, a source tap and the reading panel fit the screen', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('?lang=en')
  await page.locator('.number-picker-trigger').click()
  await page.getByRole('button', { name: 'Number 3', exact: true }).click()
  await expect(page.locator('.formula')).toHaveText('3 + 5 = 8')
  await page.locator('.relation-panel .citation-mark').click()
  await expect(page.locator('.source-popover')).toBeVisible()
  const overflow = await page.evaluate(() => document.documentElement.scrollWidth > innerWidth)
  expect(overflow).toBe(false)
  const panel = await page.locator('.relation-panel').boundingBox()
  expect(panel!.x).toBeGreaterThanOrEqual(0)
  expect(panel!.x + panel!.width).toBeLessThanOrEqual(390)
})

test('rapid switching settles correctly, idle rendering stops, and context loss preserves selection', async ({ page }) => {
  await page.goto('?lang=en')
  await expect(page.locator('.scene-number')).toHaveCount(10)
  for (const name of ['Luoshu', 'Hetu', 'Luoshu', 'Hetu']) await page.getByRole('button', { name, exact: true }).click()
  await expect(page.locator('.scene-number')).toHaveCount(10)
  await page.waitForTimeout(2200)
  const calls = await page.locator('canvas').getAttribute('data-draw-calls')
  expect(Number(calls)).toBeGreaterThan(0)
  expect(Number(calls)).toBeLessThan(30)
  const idleFrame = await page.locator('canvas').getAttribute('data-render-frame')
  await page.waitForTimeout(350)
  await expect(page.locator('canvas')).toHaveAttribute('data-render-frame', idleFrame!)
  await page.getByRole('button', { name: 'Number 7', exact: true }).click()
  await page.locator('canvas').evaluate(canvas => (canvas as HTMLCanvasElement).getContext('webgl2')?.getExtension('WEBGL_lose_context')?.loseContext())
  await expect(page.locator('.experience')).toHaveAttribute('data-renderer', 'svg')
  await expect(page.locator('.selected-number')).toContainText('07')
})

test('interface and learning dialog pass automated WCAG AA checks', async ({ page }) => {
  await page.goto('?lang=en')
  await expect(page.locator('.scene-number')).toHaveCount(10)
  const scan = () => new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa', 'wcag22aa']).analyze()
  expect((await scan()).violations).toEqual([])
  await page.getByRole('button', { name: 'Learn', exact: true }).click()
  expect((await scan()).violations).toEqual([])
})
