import { test, expect } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'

test.beforeEach(async ({ page }) => {
  await page.addInitScript(() => localStorage.setItem('hl-language', 'en'))
})
test('loads the real 3D experience and changes diagrams and relations without errors', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('?lang=en')
  await expect(page.locator('canvas')).toBeVisible()
  await expect(page.locator('.scene-number')).toHaveCount(10)
  await expect(page.locator('.guide-panel')).toHaveCount(0)
  await page.getByRole('button', { name: 'View', exact: true }).click()
  await page.getByRole('button', { name: 'Reading view', exact: true }).click()
  await page.waitForTimeout(1000)
  const canvas = await page.locator('canvas').boundingBox()
  await page.locator('canvas').click({ position: { x: canvas!.width / 2, y: canvas!.height / 2 } })
  await expect(page.locator('.selected-number')).toContainText('05')
  await expect(page.locator('.formula')).toHaveText('5 + 5 = 10')
  await page.getByRole('button', { name: 'Number 1', exact: true }).click()
  await expect(page.locator('.formula')).toHaveText('1 + 5 = 6')
  await page.getByRole('button', { name: 'Luoshu', exact: true }).click()
  await page.getByRole('button', { name: 'Balance', exact: true }).click()
  await expect(page.locator('.formula')).toHaveText('9 + 5 + 1 = 15')
  await page.getByRole('button', { name: 'Next', exact: true }).click()
  await expect(page.locator('.formula')).toHaveText('2 + 7 + 6 = 15')
  await page.getByRole('button', { name: 'Compare', exact: true }).click()
  await expect(page.locator('.scene-number')).toHaveCount(19)
  await expect(page.locator('.experience')).toHaveAttribute('data-mode', 'compare')
  await expect(page.locator('.scene-number.active')).toHaveText(['1', '1'])
  await page.waitForTimeout(1200)
  const explanation = await page.locator('.relation-panel').boundingBox()
  const labelBounds = await page.locator('.scene-number').evaluateAll(labels => labels.map(label => label.getBoundingClientRect().right))
  expect(Math.max(...labelBounds)).toBeLessThan(explanation!.x)
  expect(errors).toEqual([])
})
test('sources stay hidden until hover or focus, then show real bibliographic details', async ({ page }) => {
  await page.goto('?lang=en')
  await expect(page.locator('.source-popover')).toHaveCount(0)
  const mark = page.locator('.work-description .citation-mark')
  await mark.hover()
  await expect(page.locator('.source-popover')).toContainText('《易学启蒙》')
  await expect(page.locator('.source-popover')).toContainText('本图书第一')
  await expect(page.locator('.source-popover')).toContainText('一與六共宗')
  await expect(page.locator('.source-popover a')).toHaveAttribute('href', /wikisource/)
  await page.mouse.move(700, 50)
  await expect(page.locator('.source-popover')).toHaveCount(0)
  await mark.focus()
  await expect(page.locator('.source-popover')).toBeVisible()
  await mark.press('Escape')
  await expect(page.locator('.source-popover')).toHaveCount(0)
})
test('preserves selection during language switching and provides history and concept reading', async ({ page }) => {
  await page.goto('?lang=en')
  await page.getByRole('button', { name: 'Number 6', exact: true }).click()
  await page.getByRole('button', { name: '切换至中文' }).click()
  await expect(page.locator('html')).toHaveAttribute('lang', 'zh-CN')
  await expect(page.locator('.selected-number')).toContainText('06')
  await page.getByRole('button', { name: '入门', exact: true }).click()
  await page.getByRole('tab', { name: '源流' }).click()
  await expect(page.getByRole('dialog')).toContainText('刘牧')
  await expect(page.getByRole('dialog')).toContainText('黄宗羲')
  await page.getByRole('tab', { name: '方法' }).click()
  await expect(page.getByRole('dialog')).toContainText('观察、辨数到读经')
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
})
test('provides complete SVG interaction when WebGL2 is unavailable', async ({ page }) => {
  await page.addInitScript(() => {
    const original = HTMLCanvasElement.prototype.getContext
    HTMLCanvasElement.prototype.getContext = function (this: HTMLCanvasElement, type: string, ...args: unknown[]) { return type === 'webgl2' ? null : original.apply(this, [type, ...args] as never) } as typeof original
  })
  await page.goto('?lang=en')
  await expect(page.locator('.experience')).toHaveAttribute('data-renderer', 'svg')
  await expect(page.locator('.diagram-svg')).toBeVisible()
  await page.getByRole('button', { name: 'Number 2', exact: true }).click()
  await expect(page.locator('.formula')).toHaveText('2 + 5 = 7')
  await page.getByRole('button', { name: 'Luoshu', exact: true }).click()
  await page.getByRole('button', { name: 'Balance', exact: true }).click()
  await expect(page.locator('.formula')).toContainText('15')
  await page.getByRole('button', { name: 'Five phases', exact: true }).click()
  await page.getByRole('button', { name: 'Controlling', exact: true }).click()
  await expect(page.locator('.svg-phase-arrow')).toBeVisible()
  await expect(page.locator('.phase-formula')).toHaveText(/EarthcontrolsWater/)
  await expect(page.locator('.phase-association.from')).toContainText('2 · 5 · 8')
})
test('first visit supports immediate exploration with reduced motion and no automatic introduction', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('?lang=en')
  await expect(page.locator('.scene-number')).toHaveCount(10)
  await page.getByRole('button', { name: 'Number 1', exact: true }).click()
  await expect(page.locator('.formula')).toHaveText('1 + 5 = 6')
  await page.waitForTimeout(1500)
  await expect(page.locator('.selected-number')).toContainText('01')
  await page.getByRole('button', { name: 'About', exact: true }).click()
  await expect(page.getByRole('button', { name: /Replay introduction/ })).toHaveCount(0)
})
test('mobile controls, a source tap and the reading panel fit the screen', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('?lang=en')
  await page.locator('.number-picker-trigger').click()
  await page.getByRole('button', { name: 'Number 3', exact: true }).click()
  await expect(page.locator('.formula')).toHaveText('3 + 5 = 8')
  await page.locator('.relation-panel .citation-mark').click()
  await expect(page.locator('.source-popover')).toBeVisible()
  const overflow = await page.evaluate(() => document.documentElement.scrollWidth > innerWidth)
  expect(overflow).toBe(false)
  const panel = await page.locator('.relation-panel').boundingBox()
  expect(panel!.x).toBeGreaterThanOrEqual(0)
  expect(panel!.x + panel!.width).toBeLessThanOrEqual(390)
})

test('rapid switching settles correctly, idle rendering stops, and context loss preserves selection', async ({ page }) => {
  await page.goto('?lang=en')
  await expect(page.locator('.scene-number')).toHaveCount(10)
  for (const name of ['Luoshu', 'Hetu', 'Luoshu', 'Hetu']) await page.getByRole('button', { name, exact: true }).click()
  await expect(page.locator('.scene-number')).toHaveCount(10)
  await page.waitForTimeout(2200)
  const calls = await page.locator('canvas').getAttribute('data-draw-calls')
  expect(Number(calls)).toBeGreaterThan(0)
  expect(Number(calls)).toBeLessThan(30)
  await expect.poll(async () => {
    const frame = await page.locator('canvas').getAttribute('data-render-frame')
    await page.waitForTimeout(400)
    return await page.locator('canvas').getAttribute('data-render-frame') === frame
  }, { timeout: 10_000, intervals: [200, 400] }).toBe(true)
  await page.getByRole('button', { name: 'Number 7', exact: true }).click()
  await page.locator('canvas').evaluate(canvas => (canvas as HTMLCanvasElement).getContext('webgl2')?.getExtension('WEBGL_lose_context')?.loseContext())
  await expect(page.locator('.experience')).toHaveAttribute('data-renderer', 'svg')
  await expect(page.locator('.selected-number')).toContainText('07')
})

test('interface and learning dialog pass automated WCAG AA checks', async ({ page }) => {
  await page.goto('?lang=en')
  await expect(page.locator('.scene-number')).toHaveCount(10)
  const scan = () => new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa', 'wcag22aa']).analyze()
  expect((await scan()).violations).toEqual([])
  await page.getByRole('button', { name: 'Learn', exact: true }).click()
  expect((await scan()).violations).toEqual([])
})

test('phase associations explain both diagrams and directed steps remain consistent while paused', async ({ page }) => {
  await page.goto('?lang=en')
  await page.getByRole('button', { name: 'Five phases', exact: true }).click()
  await expect(page.locator('.phase-association')).toContainText('1 · 6')
  await expect(page.locator('.phase-association')).toContainText('Generating 1 / completing 6')
  await expect(page.locator('.scene-number.active')).toHaveText(['1', '6'])
  await page.getByRole('button', { name: 'Generating', exact: true }).click()
  await expect(page.locator('.phase-formula')).toHaveText(/WatergeneratesWood/)
  await expect(page.locator('.scene-number.active')).toHaveText(['1', '3', '6', '8'])
  await page.getByRole('button', { name: 'Play relation', exact: true }).click()
  await page.getByRole('button', { name: 'Pause', exact: true }).click()
  await expect(page.locator('.phase-formula')).toHaveText(/WatergeneratesWood/)
  await expect(page.locator('.scene-number.active')).toHaveText(['1', '3', '6', '8'])
  await page.getByRole('button', { name: 'Luoshu', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Associations', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.locator('.phase-association')).toContainText('Kan')
  await page.getByRole('button', { name: 'Generating', exact: true }).click()
  await expect(page.locator('.scene-number.active')).toHaveText(['1', '3', '4'])
  await expect(page.locator('.phase-association.to')).toContainText('Zhen')
  await expect(page.locator('.phase-association.to')).toContainText('Xun')
  await page.getByRole('button', { name: 'Earth', exact: true }).click()
  await page.getByRole('button', { name: 'Associations', exact: true }).click()
  await expect(page.locator('.phase-association')).toContainText('2 · 5 · 8')
  expect((await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa', 'wcag22aa']).analyze()).violations).toEqual([])
})

test('point totals reveal arithmetic and sources on demand', async ({ page }) => {
  await page.goto('?lang=en')
  await expect(page.locator('.count-popover')).toHaveCount(0)
  await page.getByRole('button', { name: 'Total points and calculation' }).hover()
  await expect(page.locator('.count-formula')).toHaveText('1 + 2 + 3 + 4 + 5 + 6 + 7 + 8 + 9 + 10 = 55')
  await page.locator('.count-popover .citation-mark').hover()
  await expect(page.locator('.source-popover')).toContainText('凡天地之數五十有五')
  await page.mouse.move(700, 50)
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: 'Luoshu', exact: true }).click()
  await page.getByRole('button', { name: 'Total points and calculation' }).focus()
  await expect(page.locator('.count-formula')).toHaveText('1 + 2 + 3 + 4 + 5 + 6 + 7 + 8 + 9 = 45')
  await expect(page.locator('.count-popover')).toContainText('arithmetic sum')
})

test('sound loads only on request and has operable volume and pause controls', async ({ page }) => {
  const audioRequests: string[] = []
  page.on('request', request => { if (request.url().endsWith('.mp3')) audioRequests.push(request.url()) })
  await page.goto('?lang=en')
  await expect(page.locator('.scene-number')).toHaveCount(10)
  expect(audioRequests).toEqual([])
  await page.getByRole('button', { name: 'Enable soundscape', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Disable soundscape', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect.poll(() => audioRequests.length).toBe(1)
  await expect(page.locator('.sound-popover [role=status]')).not.toContainText('Loading')
  await expect(page.getByRole('button', { name: 'Disable soundscape', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('slider', { name: 'Volume', exact: true }).fill('0.15')
  await expect(page.getByRole('slider', { name: 'Volume', exact: true })).toHaveValue('0.15')
  await page.getByRole('button', { name: 'Disable soundscape', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Enable soundscape', exact: true })).toHaveAttribute('aria-pressed', 'false')
  await page.reload()
  await expect(page.getByRole('button', { name: 'Enable soundscape', exact: true })).toHaveAttribute('aria-pressed', 'false')
})


test('failed audio can be retried and point explanations stay above the phase panel', async ({ page }) => {
  await page.route('**/*.mp3', route => route.abort())
  await page.goto('?lang=en')
  await page.getByRole('button', { name: 'Enable soundscape', exact: true }).click()
  await expect(page.locator('.sound-popover [role=status]')).toContainText('Tap to retry')
  await expect(page.getByRole('button', { name: 'Enable soundscape', exact: true })).toHaveAttribute('aria-pressed', 'false')
  await page.unroute('**/*.mp3')
  await page.getByRole('button', { name: 'Enable soundscape', exact: true }).click()
  await expect(page.locator('.sound-popover [role=status]')).not.toContainText('Loading')
  await expect(page.getByRole('button', { name: 'Disable soundscape', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: 'Five phases', exact: true }).click()
  await page.getByRole('button', { name: 'Total points and calculation' }).click()
  await expect(page.locator('.count-formula')).toBeVisible()
  const top = await page.locator('.count-formula').evaluate(element => { const rect = element.getBoundingClientRect(); return element.contains(document.elementFromPoint(rect.x + 10, rect.y + 10)) })
  expect(top).toBe(true)
})
