import { writeFileSync, mkdirSync } from 'node:fs'
import { makeDots, groupsFor } from '../src/domain/model.ts'

mkdirSync('public', { recursive: true })
const diagram = (name, x) => {
  const dots = makeDots(name)
  return `<g transform="translate(${x} 410) scale(54)"><circle r="5" fill="none" stroke="#8498a4" stroke-width=".012" opacity=".25"/>${dots.map(d => `<circle class="dot" data-number="${d.number}" cx="${d.position[0]}" cy="${d.position[2]}" r=".145" fill="${d.yang ? 'url(#white)' : 'url(#black)'}" stroke="${d.yang ? '#f2eee0' : '#8398a7'}" stroke-width=".014"/>`).join('')}${groupsFor(name).map(g => `<text x="${g.center[0] + (g.number === 10 ? 1.45 : 0)}" y="${g.center[2] + (g.number === 10 ? .05 : .98)}" text-anchor="middle" font-family="Helvetica, sans-serif" font-size=".21" fill="#8698a1">${g.number}</text>`).join('')}<text x="0" y="-5.45" text-anchor="middle" font-size=".18" fill="#7f919b">南 · SOUTH</text><text x="0" y="5.55" text-anchor="middle" font-size=".18" fill="#7f919b">北 · NORTH</text></g>`
}
writeFileSync('public/poster.svg', `<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="850" viewBox="0 0 1200 850" role="img" aria-label="Hetu and Luoshu: paired numbers and a nine-position square"><defs><radialGradient id="background"><stop stop-color="#1b2831"/><stop offset="1" stop-color="#0a0d10"/></radialGradient><radialGradient id="white" cx="30%" cy="25%"><stop stop-color="#fffef5"/><stop offset="1" stop-color="#a6a9a4"/></radialGradient><radialGradient id="black" cx="25%" cy="20%"><stop stop-color="#627e8d"/><stop offset=".4" stop-color="#253540"/><stop offset="1" stop-color="#0c141b"/></radialGradient></defs><rect width="1200" height="850" fill="url(#background)"/><g font-family="Helvetica, Arial, sans-serif" fill="#e8e8e0"><text x="70" y="76" font-size="25">Hetu × Luoshu</text><text x="70" y="104" font-size="10" letter-spacing="2" fill="#9aadb6">AN ORDER OF NUMBERS</text></g>${diagram('hetu', 315)}${diagram('luoshu', 885)}<g font-family="Helvetica, Arial, sans-serif" fill="#b5c0c0" font-size="13" letter-spacing="2"><text x="315" y="760" text-anchor="middle">HETU · 河图 / 55</text><text x="885" y="760" text-anchor="middle">LUOSHU · 洛书 / 45</text></g></svg>`)
console.log('Generated static poster from the canonical diagram data.')
